- hosts: ec2-user
  become: true
  become_method: sudo
  tasks:
    - name: Copy file to /usr/lib/systemd/system
      copy:
        src: /var/lib/jenkins/workspace/AWS-Deployment_YSD_final_project/javarestart.service
        dest: /usr/lib/systemd/system

    - name: Create symlink to /etc/systemd/system/multi-user.target.wants
      file:
        src: /usr/lib/systemd/system/javarestart.service
        dest: /etc/systemd/system/multi-user.target.wants/javarestart.service
        state: link
        force: yes

    - name: Reload the systemd to re-read configurations
      systemd:
        daemon_reload: yes

    - name: Enable the javastart service and start
      systemd:
        name: javarestart
        enabled: yes
        state: started
